[tool.poetry]
name = "kivy-project"
version = "0.1.0"
description = ""
authors = ["Anandaa69 <anandasinlapachote0@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
kivy = "^2.3.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
